/home/nova/nova-bot/.venv/lib/python3.12/site-packages/apscheduler/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import get_distribution, DistributionNotFound
Nova-bot: starter pollingâ€¦
Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/nova/nova-bot/.venv/lib/python3.12/site-packages/telegram/ext/_updater.py", line 715, in _network_loop_retry
    if not await action_cb():
           ^^^^^^^^^^^^^^^^^
  File "/home/nova/nova-bot/.venv/lib/python3.12/site-packages/telegram/ext/_updater.py", line 384, in polling_action_cb
    raise exc
  File "/home/nova/nova-bot/.venv/lib/python3.12/site-packages/telegram/ext/_updater.py", line 373, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nova/nova-bot/.venv/lib/python3.12/site-packages/telegram/ext/_extbot.py", line 618, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nova/nova-bot/.venv/lib/python3.12/site-packages/telegram/_bot.py", line 542, in decorator
    result = await func(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nova/nova-bot/.venv/lib/python3.12/site-packages/telegram/_bot.py", line 4164, in get_updates
    await self._post(
  File "/home/nova/nova-bot/.venv/lib/python3.12/site-packages/telegram/_bot.py", line 630, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/nova/nova-bot/.venv/lib/python3.12/site-packages/telegram/ext/_extbot.py", line 347, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nova/nova-bot/.venv/lib/python3.12/site-packages/telegram/_bot.py", line 658, in _do_post
    return await request.post(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/nova/nova-bot/.venv/lib/python3.12/site-packages/telegram/request/_baserequest.py", line 200, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nova/nova-bot/.venv/lib/python3.12/site-packages/telegram/request/_baserequest.py", line 381, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
